export const emptyGames = {
  id: null,
  slug: '',
  name: '',
  released: '',
  tba: null,
  background_image: '',
  rating: null,
  rating_top: null,
  ratings: [
    {
      id: null,
      title: '',
      count: null,
      percent: null,
    },
    {
      id: null,
      title: '',
      count: null,
      percent: null,
    },
    {
      id: null,
      title: '',
      count: null,
      percent: null,
    },
    {
      id: null,
      title: '',
      count: null,
      percent: null,
    },
  ],
  ratings_count: null,
  reviews_text_count: null,
  added: null,
  added_by_status: {
    yet: null,
    owned: null,
    beaten: null,
    toplay: null,
    dropped: null,
    playing: null,
  },
  metacritic: null,
  playtime: null,
  suggestions_count: null,
  updated: '',
  user_game: null,
  reviews_count: null,
  saturated_color: '',
  dominant_color: '',
  platforms: [
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: null,
      requirements_ru: null,
    },
    {
      platform: {
        id: null,
        name: '',
        slug: '',
        image: null,
        year_end: null,
        year_start: null,
        games_count: null,
        image_background: '',
      },
      released_at: '',
      requirements_en: {
        minimum: '',
        recommended: '',
      },
      requirements_ru: null,
    },
  ],
  parent_platforms: [
    {
      platform: {
        id: 1,
        name: '',
        slug: '',
      },
    },
    {
      platform: {
        id: 2,
        name: '',
        slug: '',
      },
    },
    {
      platform: {
        id: 3,
        name: '',
        slug: '',
      },
    },
  ],
  genres: [
    {
      id: 4,
      name: '',
      slug: '',
      games_count: null,
      image_background: '',
    },
    {
      id: 3,
      name: '',
      slug: '',
      games_count: null,
      image_background: '',
    },
  ],
  stores: [
    {
      id: 290375,
      store: {
        id: 3,
        name: '',
        slug: '',
        domain: '',
        games_count: null,
        image_background: '',
      },
    },
    {
      id: 438095,
      store: {
        id: 11,
        name: '',
        slug: '',
        domain: '',
        games_count: null,
        image_background: '',
      },
    },
    {
      id: 290376,
      store: {
        id: 1,
        name: '',
        slug: '',
        domain: '',
        games_count: null,
        image_background: '',
      },
    },
    {
      id: 290377,
      store: {
        id: 7,
        name: '',
        slug: '',
        domain: '',
        games_count: null,
        image_background: '',
      },
    },
    {
      id: 290378,
      store: {
        id: 2,
        name: '',
        slug: '',
        domain: '',
        games_count: null,
        image_background: '',
      },
    },
  ],
  clip: null,
  tags: [
    {
      id: 31,
      name: '',
      slug: '',
      domain: '',
      games_count: null,
      image_background: '',
    },
    {
      id: 40847,
      name: '',
      slug: '',
      language: '',
      games_count: null,
      image_background: '',
    },
    {
      id: 7,
      name: '',
      slug: '',
      language: '',
      games_count: null,
      image_background: '',
    },
    {
      id: 13,
      name: '',
      slug: '',
      language: '',
      games_count: null,
      image_background: '',
    },
  ],
  esrb_rating: {
    id: 4,
    name: '',
    slug: '',
  },
  short_screenshots: [],
};
